export const E21_COLD_START_DIAGNOSTIC_PREFIX = 'E21_COLD_START_DIAG';

export type E21ColdStartDiagnosticMarker =
  | 'PROVIDER_MOUNT'
  | 'PROVIDER_UNMOUNT'
  | 'LIVE_LISTENER_INSTALL_BEGIN'
  | 'LIVE_LISTENER_INSTALLED'
  | 'LIVE_LISTENER_INSTALL_ERROR'
  | 'LIVE_LISTENER_REMOVED'
  | 'LIVE_RESPONSE_RECEIVED'
  | 'STARTUP_EFFECT_ACTIVE'
  | 'STARTUP_EFFECT_CANCELLED'
  | 'STARTUP_PROMISE_CREATED'
  | 'STARTUP_PROMISE_REUSED'
  | 'STARTUP_PROMISE_RESOLVED'
  | 'STARTUP_PROMISE_REJECTED'
  | 'STARTUP_RESULT_DISCARDED_EFFECT_INACTIVE'
  | 'LAST_RESPONSE_REQUEST_BEGIN'
  | 'LAST_RESPONSE_RESULT_PRESENT'
  | 'LAST_RESPONSE_RESULT_NULL'
  | 'LAST_RESPONSE_RESULT_ERROR'
  | 'HANDLER_PRESENT'
  | 'HANDLER_ABSENT'
  | 'RESPONSE_SOURCE_STARTUP'
  | 'RESPONSE_SOURCE_LIVE'
  | 'RESPONSE_DISPATCHED'
  | 'PARSER_RESULT_CAREGIVER'
  | 'PARSER_RESULT_REMINDER'
  | 'PARSER_RESULT_UNSUPPORTED'
  | 'PARSER_RESULT_INVALID'
  | 'CAREGIVER_INTENT_INSTALLED'
  | 'CAREGIVER_INTENT_CONSUMED'
  | 'CAREGIVER_INTENT_CLEARED_SESSION_INVALID'
  | 'CAREGIVER_INTENT_REPLACED'
  | 'INITIAL_URL_ACCEPTED'
  | 'INITIAL_URL_REJECTED'
  | 'ROUTEGUARD_CAREGIVER_INTENT_SEEN'
  | 'ROUTEGUARD_DECISION_CAREGIVER_ALERTS'
  | 'ROUTEGUARD_DECISION_CAREGIVER_DASHBOARD';

export function emitE21ColdStartDiagnostic(
  marker: E21ColdStartDiagnosticMarker,
): void {
  if (!__DEV__) return;
  try {
    // Fixed markers only: no payload, identity, identifier, token, or metadata.
    // eslint-disable-next-line no-console
    console.info(`${E21_COLD_START_DIAGNOSTIC_PREFIX} ${marker}`);
  } catch {
    // Diagnostics must never affect notification handling or navigation.
  }
}
