import type { AppLanguage } from '@/state/PreferencesContext';
import { usePreferences } from '@/state/PreferencesContext';
const en = {
  settings: 'Settings',
  accessibility: 'Accessibility',
  language: 'Language',
  english: 'English',
  hindi: 'Hindi',
  save: 'Save',
  loading: 'Loading',
  retry: 'Retry',
  error: 'Something went wrong',
  home: 'Home',
  medicines: 'Medicines',
  schedule: 'Schedule',
  history: 'History',
  symptomInformation: 'Symptom information',
  emergencyHelp: 'Emergency help options',
  voiceControls: 'Voice controls',
  textSize: 'Text size',
  default: 'Default',
  large: 'Large',
  extraLarge: 'Extra large',
  highContrast: 'High contrast',
  reducedMotion: 'Reduced motion',
  largerControls: 'Larger controls',
  screenReaderHelp: 'Screen-reader help',
  reminderEmphasis: 'Stronger visual reminder emphasis',
  haptics: 'Haptic feedback',
  on: 'On',
  off: 'Off',
  offline: 'Offline data — may be out of date',
  dashboardTitle: 'Your dashboard',
  dashboardSubtitle: 'Medication routines at a glance.',
  interactions: 'Interaction information',
  scanPrescription: 'Scan prescription',
  inventoryRefill: 'Inventory and refill',
  medicationHistory: 'View medication history',
  caregiverDashboard: 'Open caregiver dashboard',
  signIn: 'Sign in',
  mobileNumber: 'Mobile number',
  requestCode: 'Request verification code',
  verifyCode: 'Verify code',
  verificationCode: 'Verification code',
  sendCode: 'Send verification code',
  verifyNumber: 'Verify your number',
  verifyContinue: 'Verify and continue',
  notificationSettings: 'Notification settings',
  accountSettings: 'Account and session',
  accountSettingsHelp: 'Manage this signed-in session on this device.',
  logout: 'Log out',
  logoutHint: 'Ends this session and returns to sign in.',
  logoutConfirmTitle: 'Log out of MedicineApp?',
  logoutConfirmMessage:
    'You will need to verify your mobile number to sign in again.',
  logoutCancel: 'Cancel',
  logoutError: 'Logout could not be completed. Please try again.',
  notificationsHelp:
    'Notifications can provide generic reminder alerts. They are optional and do not replace clinical care.',
  enableNotifications: 'Enable notifications',
  permissionDenied:
    'Notification permission is off. You can enable it in device settings.',
  registrationPending:
    'Push registration is unavailable. The app remains usable.',
  registrationComplete: 'This device is registered for notifications.',
  registrationOffline: 'Connect to the internet to register notifications.',
  notificationsUnsupportedRuntime:
    'Push notifications require an installed development or preview build. Other app features remain available in Expo Go.',
  notificationsUnsupportedPersonalTeam:
    'Push notifications are unavailable in this local Personal Team build. Other app features remain available.',
  openNotificationSettings: 'Open device notification settings',
  medicineSaveSuccess:
    'User-entered medicine recorded. The form is ready for another medicine.',
  medicineOnHand: 'Medicine on hand',
  currentQuantity: 'Current Quantity',
  quantityUnit: 'Quantity Unit',
  selectQuantityUnit: 'Select a unit',
  quantityUnit_tablet: 'Tablets',
  quantityUnit_capsule: 'Capsules',
  quantityUnit_ml: 'mL',
  quantityUnit_drop: 'Drops',
  quantityUnit_puff: 'Puffs',
  quantityUnit_sachet: 'Sachets',
  quantityUnit_patch: 'Patches',
  quantityUnit_unit: 'Units',
  quantityRequired: 'Enter the current quantity.',
  quantityGreaterThanZero: 'Current quantity must be greater than zero.',
  quantityInvalid: 'Enter a valid quantity with up to 4 decimal places.',
  quantityUnitRequired: 'Select a quantity unit.',
  addMedicine: 'Add Medicine',
  cancel: 'Cancel',
  deleteMedicine: 'Delete Medicine',
  deleteMedicineTitle: 'Delete medicine?',
  deleteMedicineMessage:
    'This medicine will be removed from your active medicines.',
  deleteMedicineError: 'The medicine could not be removed. Please try again.',
  editMedicine: 'Edit Medicine',
  saveChanges: 'Save Changes',
  staleMedication: 'This medicine changed elsewhere. Refresh and try again.',
  setMedicineSchedule: 'Set medicine schedule',
  noSchedule: 'No schedule',
  addSchedule: 'Add Schedule',
  editSchedule: 'Edit Schedule',
  doseQuantity: 'Dose Quantity',
  doseUnit: 'Dose Unit',
  howOften: 'How often',
  time: 'Time',
  addAnotherTime: 'Add another time',
  startDate: 'Start Date',
  endDate: 'End Date',
  untilStopped: 'Until stopped',
  schedulePartialFailure:
    'Medicine added, but the schedule could not be saved.',
  retrySchedule: 'Retry Schedule',
  captureConfirmedRetry:
    'Medicine details are confirmed. Retry will save this same reviewed medicine without confirming the image again.',
  cameraTakePhoto: 'Take photo',
  cameraTakePhotoHint:
    'Captures the medicine packaging for your review. It is not uploaded automatically.',
  cameraCaptureFailed: 'The image could not be captured. Please try again.',
  cameraChoosePhoto: 'Choose from photo library',
  cameraChooseAnotherPhoto: 'Choose another photo',
  cameraUnsupportedPhoto: 'Choose a JPEG or PNG medicine image.',
  cameraPhotoOpenFailed: 'The selected image could not be opened.',
  recognitionNoMatch:
    "We couldn't confidently match this medicine to the verified medicine list.",
  recognitionRetake:
    'Please try a clearer medicine-packaging image, choose another photo, or enter the medicine manually.',
  recognitionFailedSafe:
    'Recognition is temporarily unavailable. No medicine was created or confirmed.',
  recognitionExpired:
    'This recognition session expired. Retake the photo or choose another image.',
  recognitionQualityAdvisory:
    'Image quality may be improved with steadier focus and clearer lighting.',
  recognitionRetakeAction: 'Retake photo',
  recognitionChooseAnotherAction: 'Choose another photo',
  recognitionManualAction: 'Enter medicine manually',
  recognitionCancelAction: 'Cancel recognition',
  caregiverAccessUnavailable: 'Caregiver access is not available',
  caregiverAccessUnavailableMessage:
    'This account does not have caregiver access. Your patient experience remains available.',
  caregiverReturnHome: 'Return to patient home',
  caregiverTemporaryFailure:
    'Caregiver information is temporarily unavailable.',
  caregiverTryAgain: 'Try again',
} as const;
const hi: Partial<Record<keyof typeof en, string>> = {
  settings: 'सेटिंग्स',
  accessibility: 'सुलभता',
  language: 'भाषा',
  english: 'अंग्रेज़ी',
  hindi: 'हिन्दी',
  save: 'सहेजें',
  loading: 'लोड हो रहा है',
  retry: 'फिर प्रयास करें',
  error: 'कुछ गलत हुआ',
  home: 'होम',
  medicines: 'दवाइयाँ',
  schedule: 'समय-सारणी',
  history: 'इतिहास',
  symptomInformation: 'लक्षण संबंधी जानकारी',
  emergencyHelp: 'आपातकालीन सहायता विकल्प',
  voiceControls: 'वॉइस नियंत्रण',
  textSize: 'पाठ का आकार',
  default: 'सामान्य',
  large: 'बड़ा',
  extraLarge: 'बहुत बड़ा',
  highContrast: 'उच्च कंट्रास्ट',
  reducedMotion: 'कम गति',
  largerControls: 'बड़े नियंत्रण',
  screenReaderHelp: 'स्क्रीन रीडर सहायता',
  reminderEmphasis: 'रिमाइंडर पर अधिक दृश्य जोर',
  haptics: 'हैप्टिक प्रतिक्रिया',
  on: 'चालू',
  off: 'बंद',
  offline: 'ऑफ़लाइन डेटा — पुराना हो सकता है',
  dashboardTitle: 'आपका डैशबोर्ड',
  dashboardSubtitle: 'दवा की दिनचर्या एक नज़र में।',
  interactions: 'दवा परस्पर क्रिया जानकारी',
  scanPrescription: 'पर्चा स्कैन करें',
  inventoryRefill: 'स्टॉक और रीफिल',
  medicationHistory: 'दवा इतिहास देखें',
  caregiverDashboard: 'देखभालकर्ता डैशबोर्ड खोलें',
  signIn: 'साइन इन करें',
  mobileNumber: 'मोबाइल नंबर',
  requestCode: 'सत्यापन कोड माँगें',
  verifyCode: 'कोड सत्यापित करें',
  verificationCode: 'सत्यापन कोड',
  sendCode: 'सत्यापन कोड भेजें',
  verifyNumber: 'अपना नंबर सत्यापित करें',
  verifyContinue: 'सत्यापित करके आगे बढ़ें',
  notificationSettings: 'सूचना सेटिंग्स',
  accountSettings: 'खाता और सत्र',
  accountSettingsHelp: 'इस डिवाइस पर साइन-इन सत्र प्रबंधित करें।',
  logout: 'लॉग आउट करें',
  logoutHint: 'यह सत्र समाप्त करके साइन इन स्क्रीन पर लौटता है।',
  logoutConfirmTitle: 'MedicineApp से लॉग आउट करें?',
  logoutConfirmMessage:
    'फिर से साइन इन करने के लिए आपको अपना मोबाइल नंबर सत्यापित करना होगा।',
  logoutCancel: 'रद्द करें',
  logoutError: 'लॉग आउट पूरा नहीं हो सका। कृपया फिर प्रयास करें।',
  notificationsHelp:
    'सूचनाएँ सामान्य रिमाइंडर दे सकती हैं। वे वैकल्पिक हैं और चिकित्सकीय देखभाल का विकल्प नहीं हैं।',
  enableNotifications: 'सूचनाएँ चालू करें',
  permissionDenied:
    'सूचना अनुमति बंद है। आप इसे डिवाइस सेटिंग्स में चालू कर सकते हैं।',
  registrationPending:
    'पुश पंजीकरण उपलब्ध नहीं है। ऐप का उपयोग जारी रखा जा सकता है।',
  registrationComplete: 'यह डिवाइस सूचनाओं के लिए पंजीकृत है।',
  registrationOffline: 'सूचनाएँ पंजीकृत करने के लिए इंटरनेट से जुड़ें।',
  notificationsUnsupportedRuntime:
    'पुश सूचनाओं के लिए इंस्टॉल किया गया डेवलपमेंट या प्रीव्यू बिल्ड आवश्यक है। Expo Go में ऐप की अन्य सुविधाएँ उपलब्ध रहती हैं।',
  notificationsUnsupportedPersonalTeam:
    'इस स्थानीय Personal Team बिल्ड में पुश सूचनाएँ उपलब्ध नहीं हैं। ऐप की अन्य सुविधाएँ उपलब्ध रहती हैं।',
  openNotificationSettings: 'डिवाइस सूचना सेटिंग्स खोलें',
  medicineSaveSuccess:
    'उपयोगकर्ता द्वारा दर्ज दवा सहेजी गई। फ़ॉर्म दूसरी दवा के लिए तैयार है।',
  medicineOnHand: 'उपलब्ध दवा',
  currentQuantity: 'वर्तमान मात्रा',
  quantityUnit: 'मात्रा की इकाई',
  selectQuantityUnit: 'इकाई चुनें',
  quantityUnit_tablet: 'गोलियाँ',
  quantityUnit_capsule: 'कैप्सूल',
  quantityUnit_ml: 'मिलीलीटर',
  quantityUnit_drop: 'बूँदें',
  quantityUnit_puff: 'पफ',
  quantityUnit_sachet: 'सैशे',
  quantityUnit_patch: 'पैच',
  quantityUnit_unit: 'इकाइयाँ',
  quantityRequired: 'वर्तमान मात्रा दर्ज करें।',
  quantityGreaterThanZero: 'वर्तमान मात्रा शून्य से अधिक होनी चाहिए।',
  quantityInvalid: 'अधिकतम 4 दशमलव स्थानों वाली मान्य मात्रा दर्ज करें।',
  quantityUnitRequired: 'मात्रा की इकाई चुनें।',
  addMedicine: 'दवा जोड़ें',
  cancel: 'रद्द करें',
  deleteMedicine: 'दवा हटाएँ',
  deleteMedicineTitle: 'दवा हटाएँ?',
  deleteMedicineMessage: 'यह दवा आपकी सक्रिय दवाओं से हटा दी जाएगी।',
  deleteMedicineError: 'दवा हटाई नहीं जा सकी। कृपया फिर प्रयास करें।',
  editMedicine: 'दवा संपादित करें',
  saveChanges: 'बदलाव सहेजें',
  staleMedication: 'यह दवा कहीं और बदली गई है। रीफ़्रेश करके फिर प्रयास करें।',
  setMedicineSchedule: 'दवा की समय-सारणी बनाएँ',
  noSchedule: 'कोई समय-सारणी नहीं',
  addSchedule: 'समय-सारणी जोड़ें',
  editSchedule: 'समय-सारणी संपादित करें',
  doseQuantity: 'खुराक की मात्रा',
  doseUnit: 'खुराक की इकाई',
  howOften: 'कितनी बार',
  time: 'समय',
  addAnotherTime: 'एक और समय जोड़ें',
  startDate: 'आरंभ तिथि',
  endDate: 'समाप्ति तिथि',
  untilStopped: 'रोकने तक',
  schedulePartialFailure: 'दवा जोड़ दी गई, लेकिन समय-सारणी सहेजी नहीं जा सकी।',
  retrySchedule: 'समय-सारणी फिर प्रयास करें',
  captureConfirmedRetry:
    'दवा की जानकारी की पुष्टि हो चुकी है। फिर प्रयास करने पर चित्र की दोबारा पुष्टि किए बिना यही समीक्षा की गई दवा सहेजी जाएगी।',
  cameraTakePhoto: 'फ़ोटो लें',
  cameraTakePhotoHint:
    'आपकी समीक्षा के लिए दवा की पैकेजिंग की फ़ोटो लेता है। यह अपने आप अपलोड नहीं होती।',
  cameraCaptureFailed: 'फ़ोटो नहीं ली जा सकी। कृपया फिर प्रयास करें।',
  cameraChoosePhoto: 'फ़ोटो लाइब्रेरी से चुनें',
  cameraChooseAnotherPhoto: 'दूसरी फ़ोटो चुनें',
  cameraUnsupportedPhoto: 'JPEG या PNG दवा की फ़ोटो चुनें।',
  cameraPhotoOpenFailed: 'चुनी गई फ़ोटो खोली नहीं जा सकी।',
  recognitionNoMatch:
    'हम इस दवा का सत्यापित दवा सूची से भरोसेमंद मिलान नहीं कर सके।',
  recognitionRetake:
    'दवा की पैकेजिंग की अधिक साफ़ फ़ोटो लें, दूसरी फ़ोटो चुनें या दवा की जानकारी स्वयं दर्ज करें।',
  recognitionFailedSafe:
    'पहचान सेवा अभी उपलब्ध नहीं है। कोई दवा बनाई या पुष्टि नहीं की गई।',
  recognitionExpired:
    'यह पहचान सत्र समाप्त हो गया है। फिर फ़ोटो लें या दूसरी फ़ोटो चुनें।',
  recognitionQualityAdvisory:
    'स्थिर फ़ोकस और बेहतर रोशनी से फ़ोटो की गुणवत्ता सुधर सकती है।',
  recognitionRetakeAction: 'फिर फ़ोटो लें',
  recognitionChooseAnotherAction: 'दूसरी फ़ोटो चुनें',
  recognitionManualAction: 'दवा स्वयं दर्ज करें',
  recognitionCancelAction: 'पहचान रद्द करें',
  caregiverAccessUnavailable: 'देखभालकर्ता पहुँच उपलब्ध नहीं है',
  caregiverAccessUnavailableMessage:
    'इस खाते में देखभालकर्ता पहुँच नहीं है। रोगी अनुभव उपलब्ध रहता है।',
  caregiverReturnHome: 'रोगी होम पर लौटें',
  caregiverTemporaryFailure:
    'देखभालकर्ता की जानकारी अस्थायी रूप से उपलब्ध नहीं है।',
  caregiverTryAgain: 'फिर प्रयास करें',
};
export type TranslationKey = keyof typeof en;
export function translate(language: AppLanguage, key: TranslationKey): string {
  return language === 'hi-IN' ? (hi[key] ?? en[key]) : en[key];
}
export function localeFor(language: AppLanguage): string {
  return language;
}
export function useTranslation() {
  const { language } = usePreferences();
  return { language, t: (key: TranslationKey) => translate(language, key) };
}
