import type { AppLanguage } from '@/state/PreferencesContext';
import { usePreferences } from '@/state/PreferencesContext';
const en = {
  settings: 'Settings',
  accessibility: 'Accessibility',
  language: 'Language',
  english: 'English',
  hindi: 'Hindi',
  save: 'Save',
  loading: 'Loading',
  reminderRetry: 'Retry',
  error: 'Something went wrong',
  home: 'Home',
  medicines: 'Medicines',
  schedule: 'Schedule',
  history: 'History',
  symptomInformation: 'Symptom information',
  emergencyHelp: 'Emergency help options',
  voiceControls: 'Voice controls',
  textSize: 'Text size',
  default: 'Default',
  large: 'Large',
  extraLarge: 'Extra large',
  highContrast: 'High contrast',
  reducedMotion: 'Reduced motion',
  largerControls: 'Larger controls',
  screenReaderHelp: 'Screen-reader help',
  reminderEmphasis: 'Stronger visual reminder emphasis',
  haptics: 'Haptic feedback',
  on: 'On',
  off: 'Off',
  offline: 'Offline data — may be out of date',
  dashboardTitle: 'Your dashboard',
  dashboardSubtitle: 'Medication routines at a glance.',
  interactions: 'Interaction information',
  scanPrescription: 'Scan prescription',
  inventoryRefill: 'Inventory and refill',
  medicationHistory: 'View medication history',
  caregiverDashboard: 'Open caregiver dashboard',
  familyTitle: 'Family & Caregivers',
  familySubtitle: 'Choose exactly what an authorized caregiver may see.',
  familyLoading: 'Loading family and caregiver access',
  familyLoadError:
    'Family and caregiver access could not be loaded. Please try again.',
  familyActionError:
    'The caregiver access change could not be completed. Please try again.',
  familyPhoneError: 'Enter a valid 10-digit Indian mobile number.',
  familyEmailError: 'Enter a valid caregiver email address.',
  familyPermissionError: 'Choose at least one permission.',
  familyAuthorizedCaregivers: 'Authorized caregivers',
  familyNoAuthorizedCaregivers: 'No authorized caregivers',
  familyPendingInvitations: 'Pending invitations',
  familyNoPendingInvitations: 'No pending invitations',
  familyPendingStatus: 'Waiting for the caregiver to accept or decline.',
  familyAddCaregiver: 'Add caregiver',
  familySharingExplanation:
    'The caregiver will see only the information you select. You can change or revoke access later.',
  familyCaregiverPhone: 'Caregiver mobile number',
  familyCaregiverEmail: 'Caregiver email address',
  familyInviteUsing: 'Invite using',
  familyInvitePhone: 'Phone',
  familyInviteEmail: 'Email',
  familySendInvitation: 'Send invitation',
  familyPermissionAlerts: 'Receive medication alerts',
  familyPermissionMedications: 'View medications',
  familyPermissionAdherence: 'View medication adherence',
  familyNoPermissions: 'No permissions selected',
  familyAccept: 'Accept invitation',
  familyDecline: 'Decline invitation',
  familySharingOn: 'Sharing is on',
  familySharingOff: 'Sharing is off',
  familySavePermissions: 'Save permissions',
  familyRevoke: 'Revoke caregiver access',
  familyRevokeTitle: 'Revoke caregiver access?',
  familyRevokeMessage:
    'This caregiver will immediately lose access to your shared information.',
  familyCancel: 'Cancel',
  signIn: 'Sign in',
  mobileNumber: 'Mobile number',
  requestCode: 'Request verification code',
  verifyCode: 'Verify code',
  verificationCode: 'Verification code',
  sendCode: 'Send verification code',
  verifyNumber: 'Verify your number',
  verifyContinue: 'Verify and continue',
  notificationSettings: 'Notification settings',
  accountSettings: 'Account and session',
  accountSettingsHelp: 'Manage this signed-in session on this device.',
  logout: 'Log out',
  logoutHint: 'Ends this session and returns to sign in.',
  logoutConfirmTitle: 'Log out?',
  logoutConfirmMessage:
    'Are you sure you want to log out of MedicineApp on this device?',
  logoutCancel: 'Cancel',
  logoutError: 'Logout could not be completed. Please try again.',
  caregiverEmailTitle: 'Verified email',
  caregiverEmailHelp:
    'Add and verify an email for future caregiver invitation delivery. This does not change your phone sign-in.',
  caregiverEmailAddress: 'Email address',
  caregiverEmailRequest: 'Send verification code',
  caregiverEmailCode: '6-digit email verification code',
  caregiverEmailVerify: 'Verify email',
  caregiverEmailResend: 'Resend code',
  caregiverEmailUseDifferent: 'Use a different email',
  caregiverEmailReplace: 'Replace verified email',
  caregiverEmailPending: 'Verification pending',
  caregiverEmailVerified: 'Verified email',
  caregiverEmailLoadFailed: 'Email verification status could not be loaded.',
  caregiverEmailActionFailed:
    'Email verification could not be completed. Please try again.',
  caregiverEmailCooldown: 'Please wait before requesting another code.',
  caregiverEmailInvalidCode: 'The verification code is incorrect.',
  caregiverEmailExpired:
    'The verification code has expired. Request a new code.',
  caregiverEmailExhausted:
    'Too many incorrect attempts. Request a new verification code.',
  caregiverEmailUnavailable:
    'Email verification is temporarily unavailable. Your account is unchanged.',
  notificationsHelp:
    'Notifications can provide generic reminder alerts. They are optional and do not replace clinical care.',
  enableNotifications: 'Enable notifications',
  permissionDenied:
    'Notification permission is off. You can enable it in device settings.',
  registrationPending:
    'Push registration is unavailable. The app remains usable.',
  registrationComplete: 'This device is registered for notifications.',
  registrationOffline: 'Connect to the internet to register notifications.',
  registrationRateLimited:
    'Notification registration is temporarily limited. Please try again shortly.',
  notificationsUnsupportedRuntime:
    'Push notifications require an installed development or preview build. Other app features remain available in Expo Go.',
  notificationsUnsupportedPersonalTeam:
    'Push notifications are unavailable in this local Personal Team build. Other app features remain available.',
  openNotificationSettings: 'Open device notification settings',
  medicineReminder: 'Medicine reminder',
  reminderPushBody: "It's time to check your medicine schedule.",
  taken: 'Taken',
  snooze: 'Snooze',
  skip: 'Skip',
  markedAsTaken: 'Marked as taken',
  doseSkipped: 'Dose skipped',
  reminderSnoozed: 'Reminder snoozed',
  loadingReminder: 'Loading reminder',
  unableToLoadReminder:
    'Unable to load reminder. No medication action was recorded.',
  retry: 'Retry',
  scheduledFor: 'Scheduled for',
  dose: 'Dose',
  reminderNoLongerUpdatable: 'This reminder can no longer be updated.',
  reminderActionFailed:
    'The reminder action could not be recorded. Please try again.',
  reminderSafetyBoundary:
    'These actions record your report or postpone this reminder only. They do not change your medication schedule or provide missed-dose advice.',
  medicineSaveSuccess:
    'User-entered medicine recorded. The form is ready for another medicine.',
  medicineOnHand: 'Medicine on hand',
  currentQuantity: 'Current Quantity',
  quantityUnit: 'Quantity Unit',
  selectQuantityUnit: 'Select a unit',
  quantityUnit_tablet: 'Tablets',
  quantityUnit_capsule: 'Capsules',
  quantityUnit_ml: 'mL',
  quantityUnit_drop: 'Drops',
  quantityUnit_puff: 'Puffs',
  quantityUnit_sachet: 'Sachets',
  quantityUnit_patch: 'Patches',
  quantityUnit_unit: 'Units',
  quantityRequired: 'Enter the current quantity.',
  quantityGreaterThanZero: 'Current quantity must be greater than zero.',
  quantityInvalid: 'Enter a valid quantity with up to 4 decimal places.',
  quantityUnitRequired: 'Select a quantity unit.',
  addMedicine: 'Add Medicine',
  cancel: 'Cancel',
  deleteMedicine: 'Delete Medicine',
  deleteMedicineTitle: 'Delete medicine?',
  deleteMedicineMessage:
    'This medicine will be removed from your active medicines.',
  deleteMedicineError: 'The medicine could not be removed. Please try again.',
  editMedicine: 'Edit Medicine',
  saveChanges: 'Save Changes',
  staleMedication: 'This medicine changed elsewhere. Refresh and try again.',
  setMedicineSchedule: 'Set medicine schedule',
  scheduleReminders: 'Schedule reminders',
  scheduleRemindersHint:
    'When on, this schedule becomes active and creates reminder occurrences.',
  scheduleRemindersEditHint:
    'Current reminder state. Use schedule lifecycle controls to pause, resume, or cancel.',
  noSchedule: 'No schedule',
  addSchedule: 'Add Schedule',
  editSchedule: 'Edit Schedule',
  doseQuantity: 'Dose Quantity',
  doseUnit: 'Dose Unit',
  howOften: 'How often',
  time: 'Time',
  addAnotherTime: 'Add another time',
  startDate: 'Start Date',
  endDate: 'End Date',
  untilStopped: 'Until stopped',
  schedulePartialFailure:
    'Medicine added, but the schedule could not be saved.',
  retrySchedule: 'Retry Schedule',
  captureConfirmedRetry:
    'Medicine details are confirmed. Retry will save this same reviewed medicine without confirming the image again.',
  cameraTakePhoto: 'Take photo',
  cameraTakePhotoHint:
    'Captures the medicine packaging for your review. It is not uploaded automatically.',
  cameraCaptureFailed: 'The image could not be captured. Please try again.',
  cameraChoosePhoto: 'Choose from photo library',
  cameraChooseAnotherPhoto: 'Choose another photo',
  cameraUnsupportedPhoto: 'Choose a JPEG or PNG medicine image.',
  cameraPhotoOpenFailed: 'The selected image could not be opened.',
  recognitionNoMatch:
    "We couldn't confidently match this medicine to the verified medicine list.",
  recognitionRetake:
    'Please try a clearer medicine-packaging image, choose another photo, or enter the medicine manually.',
  recognitionFailedSafe:
    'Recognition is temporarily unavailable. No medicine was created or confirmed.',
  recognitionExpired:
    'This recognition session expired. Retake the photo or choose another image.',
  recognitionQualityAdvisory:
    'Image quality may be improved with steadier focus and clearer lighting.',
  recognitionRetakeAction: 'Retake photo',
  recognitionChooseAnotherAction: 'Choose another photo',
  recognitionManualAction: 'Enter medicine manually',
  recognitionCancelAction: 'Cancel recognition',
  caregiverAccessUnavailable: 'Caregiver access is not available',
  caregiverAccessUnavailableMessage:
    'This account does not have caregiver access. Your patient experience remains available.',
  caregiverReturnHome: 'Return to patient home',
  caregiverTemporaryFailure:
    'Caregiver information is temporarily unavailable.',
  caregiverTryAgain: 'Try again',
  caregiverAlertsTitle: 'Caregiver alerts',
  caregiverAlertsSubtitle:
    'Alerts shared through an active, authorized caregiver relationship.',
  caregiverAlertsBack: 'Back to caregiver dashboard',
  caregiverAlertsLoading: 'Loading caregiver alerts',
  caregiverAlertsEmpty: 'No caregiver alerts',
  caregiverAlertsEmptyMessage: 'There are no alerts for this family member.',
  caregiverAlertAccessUnavailable: 'Caregiver alert access is unavailable',
  caregiverAlertAccessUnavailableMessage:
    'An active relationship with alert access is required.',
  caregiverAlertsFailure:
    'Caregiver alerts are temporarily unavailable. Please try again.',
  caregiverAlertsOfflineTitle: 'Caregiver alerts are offline',
  caregiverAlertsOffline:
    'Connect to the internet to refresh caregiver alerts.',
  caregiverAlertsLoadMore: 'Load more alerts',
  caregiverAlertsChooseRelationship: 'Choose a family member',
  caregiverAlertsRelationshipLabel: 'Family member',
  caregiverAlertFamilyMember: 'Family member',
  caregiverAlertWorkflowPriority: 'Workflow priority',
  caregiverAlertTimeUnavailable: 'Time unavailable',
  caregiverAlertType_reminder_unacknowledged: 'Reminder not acknowledged',
  caregiverAlertType_medication_missed: 'Medication marked as missed',
  caregiverAlertType_repeated_non_adherence:
    'Repeated missed medication activity',
  caregiverAlertType_inventory_low: 'Medication inventory is low',
  caregiverAlertType_inventory_exhausted: 'Medication inventory is exhausted',
  caregiverAlertSeverity_info: 'Information',
  caregiverAlertSeverity_attention: 'Attention',
  caregiverAlertSeverity_important: 'Important',
  caregiverAlertState_open: 'Open',
  caregiverAlertState_acknowledged: 'Acknowledged',
  caregiverAlertState_resolved: 'Resolved',
  caregiverAlertState_cancelled: 'Cancelled',
  caregiverAlertOpenDetail: 'Open caregiver alert details',
  caregiverAlertDetailTitle: 'Caregiver alert details',
  caregiverAlertDetailBack: 'Back to caregiver alerts',
  caregiverAlertDetailLoading: 'Loading caregiver alert details',
  caregiverAlertDetailFailure:
    'Caregiver alert details are temporarily unavailable. Please try again.',
  caregiverAlertDetailOfflineTitle: 'Caregiver alert details are offline',
  caregiverAlertDetailOffline:
    'Connect to the internet to load or acknowledge this caregiver alert.',
  caregiverAlertTypeLabel: 'Alert type',
  caregiverAlertSourceLabel: 'Source category',
  caregiverAlertStateLabel: 'State',
  caregiverAlertSource_reminder: 'Reminder',
  caregiverAlertSource_intake: 'Medication activity',
  caregiverAlertSource_inventory: 'Medication inventory',
  caregiverAlertSource_system: 'System',
  caregiverAlertOccurredAt: 'Occurred at',
  caregiverAlertAcknowledgedAt: 'Acknowledged at',
  caregiverAlertResolvedAt: 'Resolved at',
  caregiverAlertCancelledAt: 'Cancelled at',
  caregiverAlertAcknowledge: 'Acknowledge',
  caregiverAlertRefresh: 'Refresh alert',
  caregiverAlertConflict:
    'This alert changed. Refresh to see its current state.',
  caregiverAlertRateLimited:
    'Caregiver alert requests are temporarily limited. Please wait and try again.',
  caregiverPreferencesEntry: 'Alert preferences',
  caregiverPreferencesEntryHint:
    'Choose which authorized alerts you want to receive for this family member.',
  caregiverPreferencesTitle: 'Caregiver alert preferences',
  caregiverPreferencesSubtitle:
    'Choose alerts for this family member. These settings do not change medicines or care instructions.',
  caregiverPreferencesLoading: 'Loading caregiver alert preferences',
  caregiverPreferencesBack: 'Back to caregiver dashboard',
  caregiverPreferencesNotConfigured:
    'No preferences have been saved yet. Opening this screen did not create any settings.',
  caregiverPreferencesReceiveAlerts: 'Receive alerts',
  caregiverPreferencesReceiveAlertsHint:
    'Turn all caregiver alert notifications on or off without changing family access.',
  caregiverPreferencesAlertTypes: 'Alert types',
  caregiverPreferencesMinimumSeverity: 'Minimum alert level',
  caregiverPreferencesMinimumSeverityHint:
    'You will receive the selected level and more important alerts.',
  caregiverPreferencesSeverity_info: 'Information and above',
  caregiverPreferencesSeverity_attention: 'Attention and above',
  caregiverPreferencesSeverity_important: 'Important only',
  caregiverPreferencesEscalation: 'Escalation alerts',
  caregiverPreferencesEscalationHint:
    'Allow follow-up escalation when the alert workflow requires it.',
  caregiverPreferencesQuietHours: 'Quiet hours',
  caregiverPreferencesQuietHoursHint:
    'Alerts may be suppressed during this local-time window, including overnight.',
  caregiverPreferencesQuietStart: 'Quiet hours start',
  caregiverPreferencesQuietEnd: 'Quiet hours end',
  caregiverPreferencesTimeHint: 'Enter a 24-hour time such as 22:00.',
  caregiverPreferencesTimezone: 'Timezone',
  caregiverPreferencesQuietHoursInvalid:
    'Enter both quiet-hour times in 24-hour HH:MM format.',
  caregiverPreferencesQuietHoursSame:
    'Quiet hours start and end must be different.',
  caregiverPreferencesSave: 'Save alert preferences',
  caregiverPreferencesSaved: 'Alert preferences saved.',
  caregiverPreferencesAccessDenied:
    'Alert preferences are unavailable for this family relationship.',
  caregiverPreferencesConflict:
    'These preferences changed elsewhere. Refresh before saving again.',
  caregiverPreferencesRefresh: 'Refresh alert preferences',
  caregiverPreferencesSaveFailed:
    'Alert preferences could not be saved. Please try again.',
  caregiverPreferencesLoadFailed:
    'Alert preferences could not be loaded. Please try again.',
} as const;
const hi: Partial<Record<keyof typeof en, string>> = {
  settings: 'सेटिंग्स',
  accessibility: 'सुलभता',
  language: 'भाषा',
  english: 'अंग्रेज़ी',
  hindi: 'हिन्दी',
  save: 'सहेजें',
  loading: 'लोड हो रहा है',
  reminderRetry: 'फिर प्रयास करें',
  error: 'कुछ गलत हुआ',
  home: 'होम',
  medicines: 'दवाइयाँ',
  schedule: 'समय-सारणी',
  history: 'इतिहास',
  symptomInformation: 'लक्षण संबंधी जानकारी',
  emergencyHelp: 'आपातकालीन सहायता विकल्प',
  voiceControls: 'वॉइस नियंत्रण',
  textSize: 'पाठ का आकार',
  default: 'सामान्य',
  large: 'बड़ा',
  extraLarge: 'बहुत बड़ा',
  highContrast: 'उच्च कंट्रास्ट',
  reducedMotion: 'कम गति',
  largerControls: 'बड़े नियंत्रण',
  screenReaderHelp: 'स्क्रीन रीडर सहायता',
  reminderEmphasis: 'रिमाइंडर पर अधिक दृश्य जोर',
  haptics: 'हैप्टिक प्रतिक्रिया',
  on: 'चालू',
  off: 'बंद',
  offline: 'ऑफ़लाइन डेटा — पुराना हो सकता है',
  dashboardTitle: 'आपका डैशबोर्ड',
  dashboardSubtitle: 'दवा की दिनचर्या एक नज़र में।',
  interactions: 'दवा परस्पर क्रिया जानकारी',
  scanPrescription: 'पर्चा स्कैन करें',
  inventoryRefill: 'स्टॉक और रीफिल',
  medicationHistory: 'दवा इतिहास देखें',
  caregiverDashboard: 'देखभालकर्ता डैशबोर्ड खोलें',
  familyTitle: 'परिवार और देखभालकर्ता',
  familySubtitle: 'चुनें कि अधिकृत देखभालकर्ता कौन-सी जानकारी देख सकता है।',
  familyLoading: 'परिवार और देखभालकर्ता पहुँच लोड हो रही है',
  familyLoadError: 'परिवार और देखभालकर्ता पहुँच लोड नहीं हुई। फिर प्रयास करें।',
  familyActionError:
    'देखभालकर्ता पहुँच में बदलाव पूरा नहीं हुआ। फिर प्रयास करें।',
  familyPhoneError: 'मान्य 10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।',
  familyEmailError: 'देखभालकर्ता का मान्य ईमेल पता दर्ज करें।',
  familyPermissionError: 'कम से कम एक अनुमति चुनें।',
  familyAuthorizedCaregivers: 'अधिकृत देखभालकर्ता',
  familyNoAuthorizedCaregivers: 'कोई अधिकृत देखभालकर्ता नहीं',
  familyPendingInvitations: 'लंबित निमंत्रण',
  familyNoPendingInvitations: 'कोई लंबित निमंत्रण नहीं',
  familyPendingStatus: 'देखभालकर्ता की स्वीकृति या अस्वीकृति की प्रतीक्षा है।',
  familyAddCaregiver: 'देखभालकर्ता जोड़ें',
  familySharingExplanation:
    'देखभालकर्ता केवल आपकी चुनी जानकारी देखेगा। आप बाद में पहुँच बदल या रद्द कर सकते हैं।',
  familyCaregiverPhone: 'देखभालकर्ता का मोबाइल नंबर',
  familyCaregiverEmail: 'देखभालकर्ता का ईमेल पता',
  familyInviteUsing: 'निमंत्रण का माध्यम',
  familyInvitePhone: 'फ़ोन',
  familyInviteEmail: 'ईमेल',
  familySendInvitation: 'निमंत्रण भेजें',
  familyPermissionAlerts: 'दवा अलर्ट प्राप्त करें',
  familyPermissionMedications: 'दवाइयाँ देखें',
  familyPermissionAdherence: 'दवा पालन देखें',
  familyNoPermissions: 'कोई अनुमति नहीं चुनी गई',
  familyAccept: 'निमंत्रण स्वीकार करें',
  familyDecline: 'निमंत्रण अस्वीकार करें',
  familySharingOn: 'साझाकरण चालू है',
  familySharingOff: 'साझाकरण बंद है',
  familySavePermissions: 'अनुमतियाँ सहेजें',
  familyRevoke: 'देखभालकर्ता की पहुँच रद्द करें',
  familyRevokeTitle: 'देखभालकर्ता की पहुँच रद्द करें?',
  familyRevokeMessage: 'यह देखभालकर्ता साझा जानकारी की पहुँच तुरंत खो देगा।',
  familyCancel: 'रद्द करें',
  signIn: 'साइन इन करें',
  mobileNumber: 'मोबाइल नंबर',
  requestCode: 'सत्यापन कोड माँगें',
  verifyCode: 'कोड सत्यापित करें',
  verificationCode: 'सत्यापन कोड',
  sendCode: 'सत्यापन कोड भेजें',
  verifyNumber: 'अपना नंबर सत्यापित करें',
  verifyContinue: 'सत्यापित करके आगे बढ़ें',
  notificationSettings: 'सूचना सेटिंग्स',
  accountSettings: 'खाता और सत्र',
  accountSettingsHelp: 'इस डिवाइस पर साइन-इन सत्र प्रबंधित करें।',
  logout: 'लॉग आउट करें',
  caregiverEmailTitle: 'सत्यापित ईमेल',
  caregiverEmailHelp:
    'भविष्य में देखभालकर्ता निमंत्रण पाने के लिए ईमेल जोड़ें और सत्यापित करें। इससे फोन साइन-इन नहीं बदलता।',
  caregiverEmailAddress: 'ईमेल पता',
  caregiverEmailRequest: 'सत्यापन कोड भेजें',
  caregiverEmailCode: '6 अंकों का ईमेल सत्यापन कोड',
  caregiverEmailVerify: 'ईमेल सत्यापित करें',
  caregiverEmailResend: 'कोड फिर भेजें',
  caregiverEmailUseDifferent: 'दूसरा ईमेल उपयोग करें',
  caregiverEmailReplace: 'सत्यापित ईमेल बदलें',
  caregiverEmailPending: 'सत्यापन लंबित है',
  caregiverEmailVerified: 'सत्यापित ईमेल',
  caregiverEmailLoadFailed: 'ईमेल सत्यापन की स्थिति लोड नहीं हुई।',
  caregiverEmailActionFailed:
    'ईमेल सत्यापन पूरा नहीं हुआ। कृपया फिर प्रयास करें।',
  caregiverEmailCooldown: 'दूसरा कोड माँगने से पहले प्रतीक्षा करें।',
  caregiverEmailInvalidCode: 'सत्यापन कोड गलत है।',
  caregiverEmailExpired:
    'सत्यापन कोड की समय-सीमा समाप्त हो गई। नया कोड माँगें।',
  caregiverEmailExhausted: 'बहुत अधिक गलत प्रयास हुए। नया सत्यापन कोड माँगें।',
  caregiverEmailUnavailable:
    'ईमेल सत्यापन अभी उपलब्ध नहीं है। आपका खाता अपरिवर्तित है।',
  logoutHint: 'यह सत्र समाप्त करके साइन इन स्क्रीन पर लौटता है।',
  logoutConfirmTitle: 'लॉग आउट करें?',
  logoutConfirmMessage:
    'क्या आप वाकई इस डिवाइस पर MedicineApp से लॉग आउट करना चाहते हैं?',
  logoutCancel: 'रद्द करें',
  logoutError: 'लॉग आउट पूरा नहीं हो सका। कृपया फिर प्रयास करें।',
  notificationsHelp:
    'सूचनाएँ सामान्य रिमाइंडर दे सकती हैं। वे वैकल्पिक हैं और चिकित्सकीय देखभाल का विकल्प नहीं हैं।',
  enableNotifications: 'सूचनाएँ चालू करें',
  permissionDenied:
    'सूचना अनुमति बंद है। आप इसे डिवाइस सेटिंग्स में चालू कर सकते हैं।',
  registrationPending:
    'पुश पंजीकरण उपलब्ध नहीं है। ऐप का उपयोग जारी रखा जा सकता है।',
  registrationComplete: 'यह डिवाइस सूचनाओं के लिए पंजीकृत है।',
  registrationOffline: 'सूचनाएँ पंजीकृत करने के लिए इंटरनेट से जुड़ें।',
  registrationRateLimited:
    'सूचना पंजीकरण अस्थायी रूप से सीमित है। कृपया थोड़ी देर बाद पुनः प्रयास करें।',
  notificationsUnsupportedRuntime:
    'पुश सूचनाओं के लिए इंस्टॉल किया गया डेवलपमेंट या प्रीव्यू बिल्ड आवश्यक है। Expo Go में ऐप की अन्य सुविधाएँ उपलब्ध रहती हैं।',
  notificationsUnsupportedPersonalTeam:
    'इस स्थानीय Personal Team बिल्ड में पुश सूचनाएँ उपलब्ध नहीं हैं। ऐप की अन्य सुविधाएँ उपलब्ध रहती हैं।',
  openNotificationSettings: 'डिवाइस सूचना सेटिंग्स खोलें',
  medicineReminder: 'दवा रिमाइंडर',
  reminderPushBody: 'अपनी दवा की समय-सारणी देखने का समय है।',
  taken: 'ले ली',
  snooze: 'बाद में याद दिलाएँ',
  skip: 'छोड़ें',
  markedAsTaken: 'दवा ली गई के रूप में दर्ज किया गया',
  doseSkipped: 'खुराक छोड़ी गई',
  reminderSnoozed: 'रिमाइंडर बाद के लिए रखा गया',
  loadingReminder: 'रिमाइंडर लोड हो रहा है',
  unableToLoadReminder:
    'रिमाइंडर लोड नहीं हो सका। कोई दवा कार्रवाई दर्ज नहीं हुई।',
  retry: 'फिर प्रयास करें',
  scheduledFor: 'निर्धारित समय',
  dose: 'खुराक',
  reminderNoLongerUpdatable: 'इस रिमाइंडर को अब अपडेट नहीं किया जा सकता।',
  reminderActionFailed: 'रिमाइंडर कार्रवाई दर्ज नहीं हो सकी। फिर प्रयास करें।',
  reminderSafetyBoundary:
    'ये कार्रवाइयाँ केवल आपकी रिपोर्ट दर्ज करती हैं या रिमाइंडर को टालती हैं। ये दवा की समय-सारणी नहीं बदलतीं और छूटी खुराक की सलाह नहीं देतीं।',
  medicineSaveSuccess:
    'उपयोगकर्ता द्वारा दर्ज दवा सहेजी गई। फ़ॉर्म दूसरी दवा के लिए तैयार है।',
  medicineOnHand: 'उपलब्ध दवा',
  currentQuantity: 'वर्तमान मात्रा',
  quantityUnit: 'मात्रा की इकाई',
  selectQuantityUnit: 'इकाई चुनें',
  quantityUnit_tablet: 'गोलियाँ',
  quantityUnit_capsule: 'कैप्सूल',
  quantityUnit_ml: 'मिलीलीटर',
  quantityUnit_drop: 'बूँदें',
  quantityUnit_puff: 'पफ',
  quantityUnit_sachet: 'सैशे',
  quantityUnit_patch: 'पैच',
  quantityUnit_unit: 'इकाइयाँ',
  quantityRequired: 'वर्तमान मात्रा दर्ज करें।',
  quantityGreaterThanZero: 'वर्तमान मात्रा शून्य से अधिक होनी चाहिए।',
  quantityInvalid: 'अधिकतम 4 दशमलव स्थानों वाली मान्य मात्रा दर्ज करें।',
  quantityUnitRequired: 'मात्रा की इकाई चुनें।',
  addMedicine: 'दवा जोड़ें',
  cancel: 'रद्द करें',
  deleteMedicine: 'दवा हटाएँ',
  deleteMedicineTitle: 'दवा हटाएँ?',
  deleteMedicineMessage: 'यह दवा आपकी सक्रिय दवाओं से हटा दी जाएगी।',
  deleteMedicineError: 'दवा हटाई नहीं जा सकी। कृपया फिर प्रयास करें।',
  editMedicine: 'दवा संपादित करें',
  saveChanges: 'बदलाव सहेजें',
  staleMedication: 'यह दवा कहीं और बदली गई है। रीफ़्रेश करके फिर प्रयास करें।',
  setMedicineSchedule: 'दवा की समय-सारणी बनाएँ',
  scheduleReminders: 'दवा रिमाइंडर',
  scheduleRemindersHint:
    'चालू होने पर यह समय-सारणी सक्रिय होकर रिमाइंडर बनाती है।',
  scheduleRemindersEditHint:
    'वर्तमान रिमाइंडर स्थिति। रोकने, फिर शुरू करने या रद्द करने के लिए समय-सारणी नियंत्रण उपयोग करें।',
  noSchedule: 'कोई समय-सारणी नहीं',
  addSchedule: 'समय-सारणी जोड़ें',
  editSchedule: 'समय-सारणी संपादित करें',
  doseQuantity: 'खुराक की मात्रा',
  doseUnit: 'खुराक की इकाई',
  howOften: 'कितनी बार',
  time: 'समय',
  addAnotherTime: 'एक और समय जोड़ें',
  startDate: 'आरंभ तिथि',
  endDate: 'समाप्ति तिथि',
  untilStopped: 'रोकने तक',
  schedulePartialFailure: 'दवा जोड़ दी गई, लेकिन समय-सारणी सहेजी नहीं जा सकी।',
  retrySchedule: 'समय-सारणी फिर प्रयास करें',
  captureConfirmedRetry:
    'दवा की जानकारी की पुष्टि हो चुकी है। फिर प्रयास करने पर चित्र की दोबारा पुष्टि किए बिना यही समीक्षा की गई दवा सहेजी जाएगी।',
  cameraTakePhoto: 'फ़ोटो लें',
  cameraTakePhotoHint:
    'आपकी समीक्षा के लिए दवा की पैकेजिंग की फ़ोटो लेता है। यह अपने आप अपलोड नहीं होती।',
  cameraCaptureFailed: 'फ़ोटो नहीं ली जा सकी। कृपया फिर प्रयास करें।',
  cameraChoosePhoto: 'फ़ोटो लाइब्रेरी से चुनें',
  cameraChooseAnotherPhoto: 'दूसरी फ़ोटो चुनें',
  cameraUnsupportedPhoto: 'JPEG या PNG दवा की फ़ोटो चुनें।',
  cameraPhotoOpenFailed: 'चुनी गई फ़ोटो खोली नहीं जा सकी।',
  recognitionNoMatch:
    'हम इस दवा का सत्यापित दवा सूची से भरोसेमंद मिलान नहीं कर सके।',
  recognitionRetake:
    'दवा की पैकेजिंग की अधिक साफ़ फ़ोटो लें, दूसरी फ़ोटो चुनें या दवा की जानकारी स्वयं दर्ज करें।',
  recognitionFailedSafe:
    'पहचान सेवा अभी उपलब्ध नहीं है। कोई दवा बनाई या पुष्टि नहीं की गई।',
  recognitionExpired:
    'यह पहचान सत्र समाप्त हो गया है। फिर फ़ोटो लें या दूसरी फ़ोटो चुनें।',
  recognitionQualityAdvisory:
    'स्थिर फ़ोकस और बेहतर रोशनी से फ़ोटो की गुणवत्ता सुधर सकती है।',
  recognitionRetakeAction: 'फिर फ़ोटो लें',
  recognitionChooseAnotherAction: 'दूसरी फ़ोटो चुनें',
  recognitionManualAction: 'दवा स्वयं दर्ज करें',
  recognitionCancelAction: 'पहचान रद्द करें',
  caregiverAccessUnavailable: 'देखभालकर्ता पहुँच उपलब्ध नहीं है',
  caregiverAccessUnavailableMessage:
    'इस खाते में देखभालकर्ता पहुँच नहीं है। रोगी अनुभव उपलब्ध रहता है।',
  caregiverReturnHome: 'रोगी होम पर लौटें',
  caregiverTemporaryFailure:
    'देखभालकर्ता की जानकारी अस्थायी रूप से उपलब्ध नहीं है।',
  caregiverTryAgain: 'फिर प्रयास करें',
  caregiverPreferencesEntry: 'अलर्ट प्राथमिकताएँ',
  caregiverPreferencesEntryHint:
    'इस परिवार सदस्य के लिए अधिकृत अलर्ट चुनें जिन्हें आप प्राप्त करना चाहते हैं।',
  caregiverPreferencesTitle: 'देखभालकर्ता अलर्ट प्राथमिकताएँ',
  caregiverPreferencesSubtitle:
    'इस परिवार सदस्य के लिए अलर्ट चुनें। ये सेटिंग दवाइयाँ या देखभाल निर्देश नहीं बदलतीं।',
  caregiverPreferencesLoading: 'देखभालकर्ता अलर्ट प्राथमिकताएँ लोड हो रही हैं',
  caregiverPreferencesBack: 'देखभालकर्ता डैशबोर्ड पर वापस जाएँ',
  caregiverPreferencesNotConfigured:
    'अभी कोई प्राथमिकता सहेजी नहीं गई है। इस स्क्रीन को खोलने से कोई सेटिंग नहीं बनी।',
  caregiverPreferencesReceiveAlerts: 'अलर्ट प्राप्त करें',
  caregiverPreferencesReceiveAlertsHint:
    'परिवार की पहुँच बदले बिना सभी देखभालकर्ता अलर्ट सूचनाएँ चालू या बंद करें।',
  caregiverPreferencesAlertTypes: 'अलर्ट के प्रकार',
  caregiverPreferencesMinimumSeverity: 'न्यूनतम अलर्ट स्तर',
  caregiverPreferencesMinimumSeverityHint:
    'आपको चुने गए स्तर और उससे अधिक महत्वपूर्ण अलर्ट मिलेंगे।',
  caregiverPreferencesSeverity_info: 'जानकारी और उससे ऊपर',
  caregiverPreferencesSeverity_attention: 'ध्यान और उससे ऊपर',
  caregiverPreferencesSeverity_important: 'केवल महत्वपूर्ण',
  caregiverPreferencesEscalation: 'एस्केलेशन अलर्ट',
  caregiverPreferencesEscalationHint:
    'अलर्ट कार्यप्रवाह में आवश्यक होने पर आगे का एस्केलेशन होने दें।',
  caregiverPreferencesQuietHours: 'शांत समय',
  caregiverPreferencesQuietHoursHint:
    'इस स्थानीय समय अवधि में, रात भर सहित, अलर्ट रोके जा सकते हैं।',
  caregiverPreferencesQuietStart: 'शांत समय शुरू',
  caregiverPreferencesQuietEnd: 'शांत समय समाप्त',
  caregiverPreferencesTimeHint: '24 घंटे का समय दर्ज करें, जैसे 22:00।',
  caregiverPreferencesTimezone: 'समय क्षेत्र',
  caregiverPreferencesQuietHoursInvalid:
    'शांत समय के दोनों समय 24 घंटे के HH:MM प्रारूप में दर्ज करें।',
  caregiverPreferencesQuietHoursSame: 'शांत समय का आरंभ और अंत अलग होना चाहिए।',
  caregiverPreferencesSave: 'अलर्ट प्राथमिकताएँ सहेजें',
  caregiverPreferencesSaved: 'अलर्ट प्राथमिकताएँ सहेजी गईं।',
  caregiverPreferencesAccessDenied:
    'इस पारिवारिक संबंध के लिए अलर्ट प्राथमिकताएँ उपलब्ध नहीं हैं।',
  caregiverPreferencesConflict:
    'ये प्राथमिकताएँ कहीं और बदल गई हैं। फिर सहेजने से पहले रीफ़्रेश करें।',
  caregiverPreferencesRefresh: 'अलर्ट प्राथमिकताएँ रीफ़्रेश करें',
  caregiverPreferencesSaveFailed:
    'अलर्ट प्राथमिकताएँ सहेजी नहीं जा सकीं। कृपया फिर प्रयास करें।',
  caregiverPreferencesLoadFailed:
    'अलर्ट प्राथमिकताएँ लोड नहीं हो सकीं। कृपया फिर प्रयास करें।',
  caregiverAlertType_reminder_unacknowledged: 'रिमाइंडर स्वीकार नहीं किया गया',
  caregiverAlertType_medication_missed: 'दवा छूटी हुई दर्ज की गई',
  caregiverAlertType_repeated_non_adherence: 'बार-बार दवा छूटने की गतिविधि',
  caregiverAlertType_inventory_low: 'दवा का स्टॉक कम है',
  caregiverAlertType_inventory_exhausted: 'दवा का स्टॉक समाप्त हो गया है',
};
export type TranslationKey = keyof typeof en;
export function translate(language: AppLanguage, key: TranslationKey): string {
  return language === 'hi-IN' ? (hi[key] ?? en[key]) : en[key];
}
export function localeFor(language: AppLanguage): string {
  return language;
}
export function useTranslation() {
  const { language } = usePreferences();
  return { language, t: (key: TranslationKey) => translate(language, key) };
}
